export enum PropertyType {
  HOTEL = "HOTEL",
  GUEST_HOUSE = "GUEST_HOUSE",
  BED_AND_BREAKFAST = "BED_AND_BREAKFAST",
  HOMESTAY = "HOMESTAY",
  HOSTEL = "HOSTEL",
  APARTHOTEL = "APARTHOTEL",
  CAPSULE_HOTEL = "CAPSULE_HOTEL",
  COUNTRY_HOUSE = "COUNTRY_HOUSE",
  FARM_STAY = "FARM_STAY",
  INN = "INN",
  LOVE_HOTEL = "LOVE_HOTEL",
  MOTEL = "MOTEL",
  RESORT = "RESORT",
  RIAD = "RIAD",
  RYOKAN = "RYOKAN",
  LODGE = "LODGE",
}

export enum PropertyFacilities {
  RESTAURANT = "RESTAURANT",
  ROOM_SERVICE = "ROOM_SERVICE",
  BAR = "BAR",
  FRONT_DESK = "FRONT_DESK",
  SAUNA = "SAUNA",
  FITNESS_CENTER = "FITNESS_CENTER",
  GARDEN = "GARDEN",
  TERRACE = "TERRACE",
  NON_SMOKING_ROOMS = "NON_SMOKING_ROOMS",
  AIRPORT_SHUTTLE = "AIRPORT_SHUTTLE",
  FAMILY_ROOMS = "FAMILY_ROOMS",
  SPA_AND_WELLNESS_CENTER = "SPA_AND_WELLNESS_CENTER",
  HOT_TUB_JAZZ = "HOT_TUB_JAZZ",
  FREE_WI_FI = "FREE_WI_FI",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  WATER_PARK = "WATER_PARK",
  ELECTRIC_VEHICLE_CHARGING_STATION = "ELECTRIC_VEHICLE_CHARGING_STATION",
  SWIMMING_POOL = "SWIMMING_POOL",
  BEACHFRONT = "BEACHFRONT",
}

export enum HotelStaffLanguages {
  ENGLISH = "ENGLISH",
  FRENCH = "FRENCH",
  ITALIAN = "ITALIAN",
  KOREAN = "KOREAN",
  UZBEK = "UZBEK",
  RUSSIAN = "RUSSIAN",
  SPANISH = "SPANISH",
}

export enum PropertyStatus {
  ACTIVE = "ACTIVE",
  SOLD = "SOLD",
  DELETE = "DELETE",
}
